export const tasks = [
    {
        level: 1,
        title: "👀 Read Articles",
        text: "Complete three beginner articles on SDLC and STLC. (🪙 20)",
        points: 20,
        completed: "false",
    },
    {
        level: 1,
        title: "📺 Watch Videos",
        text: "Watch two YouTube tutorials on basic testing concepts. (🪙 20)",
        points: 20,
        completed: "false",
    },
    {
        level: 1,
        title: "❔ Quiz",
        text: "Pass a quiz with at least 80% score on the learned concepts. (🪙 20)",
        points: 20,
        completed: "false",
    },
    {
        level: 2,
        title: "📖 Read Boring Ass theory",
        text: "Read on the theory of creating test cases. (🪙 40)",
        points: 40,
        completed: "false",
    },
    {
        level: 2,
        title: "✏️ Create a Few Test Cases",
        text: "Write 5 test cases for a sample application. (🪙 40)",
        points: 40,
        completed: "false",
    },
    {
        level: 2,
        title: "📝 Execute Test Cases",
        text: "Execute your test cases and document the results. (🪙 40)",
        points: 40,
        completed: "false",
    },
    {
        level: 3,
        title: "📖 Read Articles",
        text: "Read articles on defect life cycle and defect reporting. (🪙 40)",
        points: 40,
        completed: "false",
    },
    {
        level: 3,
        title: "🛠️ Tool Setup",
        text: "Set up a bug tracking tool (e.g., JIRA) and report 3 sample defects. (🪙 40)",
        points: 40,
        completed: "false",
    },
    {
        level: 3,
        title: "🗣️ Role-Playing",
        text: "Participate in a role-playing exercise to practice reporting and tracking defects. (🪙 40)",
        points: 40,
        completed: "false",
    },
    {
        level: 4,
        title: "📖 Read Articles",
        text: "Read articles on the fundamentals of API testing. (🪙 40)",
        points: 40,
        completed: "false",
    },
    {
        level: 4,
        title: "📺 Watch Tutorials",
        text: "Watch video tutorials on using Postman for API testing. (🪙 40)",
        points: 40,
        completed: "false",
    },
    {
        level: 4,
        title: "🛠️ Tool Setup",
        text: "Install Postman and explore its interface. (🪙 40)",
        points: 40,
        completed: "false",
    },
    {
        level: 4,
        title: "🖨️ Basic API Requests",
        text: "Create and send basic GET and POST requests using Postman. (🪙 50)",
        points: 40,
        completed: "false",
    },
    {
        level: 4,
        title: "🏇 API Testing Challenge",
        text: "Perform testing on a sample API, including creating test cases for different endpoints. (🪙 50)",
        points: 40,
        completed: "false",
    },
    {
        level: 4,
        title: "📃 Document Findings",
        text: "Document your API testing process and findings. (🪙 40)",
        points: 40,
        completed: "false",
    },
    {
        level: 5,
        title: "📺 Watch Tutorials",
        text: "Watch SQL tutorial for beginners. (🪙 40)",
        points: 40,
        completed: "false",
    },
    {
        level: 5,
        title: "📝 Practice Queries",
        text: "Write and execute 5 basic SQL queries (e.g., SELECT, INSERT). (🪙 60)",
        points: 60,
        completed: "false",
    },
    {
        level: 5,
        title: "🏇 Database Challenge",
        text: "Complete a database testing challenge using your SQL skills. (🪙 100)",
        points: 100,
        completed: "false",
    },
    {
        level: 6,
        title: "🗣️ Introductory Talk",
        text: "Suffer through me trying to teach you about for loops and stuff.  (🪙 tolko bodov na svete neexistuje, ale 100 I guess 😅😅)",
        points: 100,
        completed: "false",
    },
    {
        level: 6,
        title: "🪢 Git basics",
        text: "Get basic understanding of git - what it is, basic commands (pull, push, merge). (🪙 75)",
        points: 75,
        completed: "false",
    },
    {
        level: 6,
        title: "🌐 Learn how websites are made",
        text: "Go over basics of HTML. (🪙 75)",
        points: 75,
        completed: "false",
    },
    {
        level: 6,
        title: "🛠️ Tool Exploration",
        text: "Install VS Code and write a simple script. (🪙 50)",
        points: 50,
        completed: "false",
    },
    {
        level: 6,
        title: "🏇 Mini Project",
        text: "Write your name to a console letter by letter. (🪙 100)",
        points: 100,
        completed: "false",
    },
    {
        level: 7,
        title: "🪣 Variables, Operators and Data types",
        text: "Learn about variables and data types in Javascript.  (🪙 100)",
        points: 100,
        completed: "false"
    },
    {
        level: 7,
        title: "🤔 Conditions",
        text: "Learn about if/else and switch statements. (🪙 75)",
        points: 75,
        completed: "false"
    },
    {
        level: 7,
        title: "🪢 Loops",
        text: "Learn about for and while loops in Javascript. (🪙 75)",
        points: 75,
        completed: "false"
    },
    {
        level: 7,
        title: "📦 Objects",
        text: "Learn about objects in Javascript. (🪙 75)",
        points: 75,
        completed: "false"
    },
    {
        level: 7,
        title: "🎞️ Arrays",
        text: "Learn about arrays in Javascript. (🪙 75)",
        points: 75,
        completed: "false"
    },
    {
        level: 7,
        title: "🖥️ Node.js",
        text: "Learn basics of Node.js. (🪙 100)",
        points: 100,
        completed: "false"
    },
    {
        level: 8,
        title: "📺 Introductory Video",
        text: "Watch an introductory video on Selenium and Gherkin. (🪙 50)",
        points: 50,
        completed: "false",
    },
    {
        level: 8,
        title: "🛠️ Tool Exploration",
        text: "Install Selenium and run a simple test script. (🪙 50)",
        points: 50,
        completed: "false",
    },
    {
        level: 8,
        title: "🏇 Mini Project",
        text: "Write a basic script to automate a simple test case. (🪙 50)",
        points: 50,
        completed: "false",
    },
    {
        level: 9,
        title: "📖 Read Guides",
        text: "Read user guides for tools like TestRail. (🪙 50)",
        points: 50,
        completed: "false",
    },
    {
        level: 9,
        title: "🛠️ Tool Setup",
        text: "Set up a test project in TestRail or a similar tool. (🪙 50)",
        points: 50,
        completed: "false",
    },
    {
        level: 9,
        title: "🏇 Project Simulation",
        text: "Simulate a test cycle using the tool. (🪙 50)",
        points: 50,
        completed: "false",
    },
    {
        level: 10,
        title: "🗣️ Role-Playing",
        text: "Participate in a role-playing session to simulate defect reporting. (🪙 50)",
        points: 50,
        completed: "false",
    },
    {
        level: 10,
        title: "🎭 Group Project",
        text: "Describe how you work in a team setting. (🪙 50)",
        points: 50,
        completed: "false",
    },
    {
        level: 10,
        title: "📝 Feedback Session",
        text: "Receive and provide feedback on test cases and reports. (🪙 50)",
        points: 50,
        completed: "false",
    },
    {
        level: 11,
        title: "🗣️ Capstone Project",
        text: "Complete a full mock interview, including requirement analysis, test case writing, execution, defect reporting, and test management. (🪙 200)",
        points: 200,
        completed: "false",
    },
    {
        level: 11,
        title: "🎞️ Presentation",
        text: "Present yourself in the best light in a stressful situation. (🪙 150)",
        points: 150,
        completed: "false",
    },
    {
        level: 11,
        title: "🤔 Reflection",
        text: "Write a reflection on your learning journey and areas for improvement. (🪙 150)",
        points: 150,
        completed: "false",
    }
]